module.exports = {
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  REQUESTED_COUNTRY_NOT_AVAILABLE: "REQUESTED_COUNTRY_NOT_AVAILABLE",
  META_HEADER_NOT_PRESENT: "META_HEADER_NOT_PRESENT",
  INVALID_META_HEADER: "INVALID_META_HEADER"
};
